#!/bin/bash

echo "Installing apt dependencies"
sudo apt-get -y install curl git-core build-essential openssl libreadline6 libreadline6-dev curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-0 libsqlite3-dev sqlite3 libxml2-dev libxslt-dev autoconf libc6-dev ncurses-dev automake libtool bison subversion

if ! rvm --version;
then
  echo "Installing rvm"
  bash -s stable < <(curl -s https://raw.github.com/wayneeseguin/rvm/master/binscripts/rvm-installer)
fi
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"

if ! ruby --version;
then
  echo "Installing ruby"
  rvm install 1.9.3-p0 && rvm use 1.9.3-p0 --default
fi

if ! ruby --version;
then
  echo "Ruby is not installed!!!!!!"
  echo "Please install it manually, then install rake and run \`rake install\`"
  exit 1
fi

export DOTFILES_PATH=~/dotfiles

gem install bundler && bundle install && rake install

