# ~/.tmuxinator/default.yml
# you can make as many tabs as you wish...

name: default
root: ~/work/default
# pre_window: rvm use default
windows:
  - bash:
  - bash:
  - vim: vim
  - console:
  - bash:
