
source ~/dotfiles/vim/init.vim

source ~/dotfiles/vim/plugins.vim

source ~/dotfiles/vim/settings.vim
source ~/dotfiles/vim/mappings.vim

source ~/dotfiles/vim/navigation.vim

source ~/dotfiles/vim/macros.vim

